version: '3.8'

services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dbscript
      MYSQL_USER: dbscript
      MYSQL_PASSWORD: dbscript
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/scripts:/scripts
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:mysql

volumes:
  mysql_data:
